// events.js — Gothic Gauntlet event pools (139 actions · 141 consequences · 60 deaths)
(function() {
  const EVENT_POOLS = {
    actions: [
      "{name} scales the ruined battlements and surveys the Gauntlet from above.",
      "{name} sets a wire snare across a dark corridor using a frayed crossbow string.",
      "{name} drinks from a stone font, refilling a cracked leather canteen.",
      "{name} fashions a crude pike from a broken lance and stolen rope.",
      "{name} ambushes a lesser warrior and drives them from a cache of salted provisions.",
      "{name} digs a shallow pit trap in the mud and covers it with straw and armour scraps.",
      "{name} forms a silent pact with a nearby warrior using the old hand-signs.",
      "{name} raids an unguarded supply chest while its keeper sleeps behind a barricade.",
      "{name} retreats into the catacombs and waits out the night among the old bones.",
      "{name} smears ash and mud across their face and gorget for concealment.",
      "{name} hunts a rival through two darkened halls before losing them at a collapsed portcullis.",
      "{name} binds a gash with strips of linen torn from a dead monk's robe.",
      "{name} tests a cluster of wild mushrooms carefully before eating any.",
      "{name} lights a small torch to signal heralds and ward off the dungeon cold.",
      "{name} wades through a flooded crypt to shake off pursuers.",
      "{name} constructs a barricade of broken pews and iron candlesticks before nightfall.",
      "{name} lures a rival toward a crumbling floor section with a thrown stone.",
      "{name} backtracks along their own path to confuse anyone following their torchlight.",
      "{name} observes two other warriors from behind a shattered stained-glass window.",
      "{name} claims a high tower chamber and blocks the door with a heavy stone altar.",
      "{name} crafts a sling from a leather baldric and a river stone.",
      "{name} tracks a warrior's bootprints through soft dungeon silt for half a mile.",
      "{name} dismantles a deadfall trap and repurposes its chains and counterweights.",
      "{name} charges the central keep at dawn in a calculated raid for provisions.",
      "{name} sleeps in a stone sarcophagus, barely breathing, while footsteps echo past.",
      "{name} lowers themselves on a rope of knotted monk's robes into a lower vault.",
      "{name} feigns a mortal wound to draw another warrior into an exposed position.",
      "{name} harvests medicinal lichen from a damp dungeon wall.",
      "{name} climbs to the highest spire to scan the Gauntlet's full breadth.",
      "{name} abandons their camp at the last second as a Gauntlet beast closes in.",
      "{name} arranges decoy bedding of straw and armour to mislead searchers.",
      "{name} trades safe passage to a weaker warrior in exchange for dried meat.",
      "{name} disables a rival's spring-loaded blade trap and marks it with a skull as warning.",
      "{name} follows the sound of a death knell to scavenge whatever provisions remain.",
      "{name} hurls loose cobblestones down a spiral staircase at a pursuing warrior.",
      "{name} identifies an edible root pushing through the flagstones and pries it free.",
      "{name} sprints across the open bailey to seize a herald's supply drop first.",
      "{name} holds absolutely still for hours as warriors search the adjoining chamber.",
      "{name} marks safe routes by scratching runes into the dungeon stonework.",
      "{name} tears a cloak into strips and fashions a crude bandage kit.",
      "{name} shadows a rival warband from a safe distance, studying their patrol routes.",
      "{name} splashes through a sewage channel to mask their scent from the Gauntlet hounds.",
      "{name} lifts a dagger from a sleeping warrior's belt without waking them.",
      "{name} drives away a dungeon wolf-pack using brands torn from a burning brazier.",
      "{name} leads a rival into a thorn-choked undercroft and slips away in the dark.",
      "{name} rappels down a sheer interior wall using braided leather reins.",
      "{name} sets three crossbow-string snares in a triangle formation around their camp.",
      "{name} boils water over a smokeless fire of dried dung before drinking it.",
      "{name} signals a distant ally by angling a polished shield to catch torchlight.",
      "{name} attempts to intimidate a dungeon rat, only for the rat to stare back unimpressed.",
      "{name} practices a heroic battle pose in a cracked mirror before realizing another warrior is watching.",
      "{name} mistakes a decorative gargoyle for a Gauntlet beast and apologizes to it politely.",
      "{name} tries to skip a stone across a flooded crypt and is delighted when it actually works.",
      "{name} challenges their own echo to a duel and declares victory after a dramatic pause.",
      "{name} fashions a ‘lucky charm’ from two bones and a bent spoon, convinced it hums with power.",
      "{name} attempts to pet a dungeon cat, which immediately steals a strip of their rations.",
      "{name} whispers a rousing speech to a suit of rusted armor, feeling oddly encouraged afterward.",
      "{name} tests a mysterious glowing mushroom by poking it with a stick… which now glows too.",
      "{name} practices stealth by sneaking past an empty hallway with exaggerated care.",
      "{name} tries to barter with a raven using shiny pebbles; the raven takes them all and leaves.",
      "{name} reenacts a legendary duel using a broom handle before tripping over their own cloak.",
      "{name} attempts to decipher ancient runes that turn out to be a child’s doodles in the dust.",
      "{name} salutes a herald’s banner only to realize it’s just a torn curtain caught on a spike.",
      "{name} invents a victory song and hums it loudly enough to alert three nearby warriors.",
      "{name} attempts to juggle three dungeon skulls, succeeding for exactly one glorious second.",
      "{name} mistakes a pile of rubble for a sleeping beast and tiptoes around it dramatically.",
      "{name} tries to train a dungeon beetle to fetch pebbles; the beetle wanders off immediately.",
      "{name} practices their ‘heroic stride’ across the bailey, tripping on the first loose flagstone.",
      "{name} attempts to intimidate a torch sconce into giving more light by glaring at it intensely.",
      "{name} hides a reserve of black bread under a loose flagstone, memorising the location.",
      "{name} delivers a stirring monologue to a pile of rubble, then bows to the silence.",
      "{name} carefully arranges three dungeon pebbles into what they insist is a tactical map.",
      "{name} spots a rival's footprints, follows them for an hour, and arrives back at their own camp.",
      "{name} names their sword after a lengthy ceremony and immediately drops it in a puddle.",
      "{name} constructs an elaborate scarecrow from a broken halberd and a moth-eaten tabard to confuse searchers.",
      "{name} attempts to whistle innocuously while creeping through an occupied chamber, which helps no one.",
      "{name} writes a threatening message on a dungeon wall, runs out of space, and trails off with '...etc.'",
      "{name} discovers a puddle that perfectly reflects the ceiling and spends ten minutes philosophically staring into it.",
      "{name} strikes a majestic pose on a parapet until a pigeon lands on their head and they must hold perfectly still.",
      "{name} attempts to befriend a dungeon spider, names it, and leaves it in charge of guarding their camp.",
      "{name} practices their victory speech, editing it extensively, and settles on simply: 'I win.'",
      "{name} stacks loose stones into a cairn, labels it 'HERE LIES MY HUNGER' and feels much better.",
      "{name} ties a bell to a rat and releases it toward enemy territory as a crude but oddly effective alarm.",
      "{name} attempts a running leap across a gap, sticks the landing perfectly, and celebrates alone.",
      "{name} builds a tiny fire, stares into it dramatically, and feels this was the right decision.",
      "{name} scrawls a list of every warrior still alive, crosses out their own name by accident, and panics briefly.",
      "{name} spends twenty minutes teaching themselves to crack their knuckles loudly as an intimidation technique.",
      "{name} ties their bootlaces together for warmth and immediately forgets they have done this.",
      "{name} discovers someone else's hidden stash, eats half of it, carefully replaces the wrapping, and leaves.",
      "{name} attempts to read the stars for tactical guidance but the sky is overcast and they guess anyway.",
      "{name} finds a dungeon corridor that slopes slightly upward and announces loudly that they are 'taking the high ground.'",
      "{name} discovers an ancient mural depicting a great warrior and spends several minutes noting the resemblance to themselves.",
      "{name} polishes their weapon so thoroughly that it reflects sunlight into an enemy's eyes entirely by accident.",
      "{name} practices falling silently by falling off a low ledge repeatedly until they stop making noise.",
      "{name} collects shed snake skins and arranges them around camp as an implied threat.",
      "{name} attempts to meditate on a cold stone floor and nearly falls asleep three times before giving up.",
      "{name} carves a rough self-portrait into a dungeon wall, steps back, and is quietly satisfied.",
      "{name} fashions a crude periscope from two polished belt buckles and peers around a corner feeling very clever.",
      "{name} recites a war ballad under their breath while sharpening a blade — slightly off-key throughout.",
      "{name} spots a distant warrior and waves, then pretends they were just stretching when they wave back.",
      "{name} constructs a decoy campfire using an orange cloth and a stick, which fools nobody but delights them.",
      "{name} arranges a line of dungeon bones across a passage as a tripwire alarm, adding a small sign reading 'NOTICE'.",
      "{name} invents a secret handshake with themselves in case they ever need to verify their own identity.",
      "{name} attempts to identify edible berries using a system of their own devising, which is mostly guesswork.",
      "{name} writes 'TRAP' in the dust next to an obvious hazard as a professional courtesy.",
      "{name} stitches a motivational phrase into their sleeve lining in case morale drops further.",
      "{name} rearranges a pile of rocks to spell out their own name, then kicks it apart before anyone sees.",
      "{name} ties a long thread to their ankle before entering a maze and feels extremely prepared.",
      "{name} discovers a dungeon cat, solemnly deputises it as camp sentinel, and promotes it to general by midday.",
      "{name} finds a broken hourglass and carries it anyway, reasoning that time is relative.",
      "{name} drafts a formal declaration of war addressed to the Gauntlet itself, signs it, and hides it under a rock.",
      "{name} practices screaming silently for use in situations where a regular scream would be inconvenient.",
      "{name} locates a crumbling arch, props it up with a stick, and marks it 'LOAD BEARING — DO NOT REMOVE'.",
      "{name} sneaks into an abandoned camp, rearranges everything slightly, and retreats to observe the confusion.",
      "{name} spots a footprint in the mud, crouches over it for several minutes, and concludes it is large.",
      "{name} attempts to throw their voice to distract a nearby warrior, achieving only a slightly louder version of their own voice.",
      "{name} constructs a miniature trebuchet from a bent spoon and a twig, tests it once, and is thrilled by the results.",
      "{name} selects a large rock as a 'backup weapon', names it Brunhilde, and carries it with quiet confidence.",
      "{name} discovers a room full of old armour, tries several pieces on for fit, and leaves better dressed.",
      "{name} draws a detailed treasure map to their own current location and hides it somewhere confusing.",
      "{name} sets up an elaborate series of leaning-stick alarms around their camp, immediately walks through them, and resets them.",
      "{name} practices walking backward to disguise their direction of travel and bumps into a wall with great dignity.",
      "{name} finds a dungeon lute with two strings, plays a brief chord, and decides this is enough music for now.",
      "{name} counts their remaining provisions with great ceremony, announces the results gravely, and eats one anyway.",
      "{name} constructs an argument for why the dungeon smell is actually bracing and healthful, and half-believes it.",
      "{name} pretends to examine something very interesting on the ground whenever another warrior looks in their direction.",
      "{name} finds a discarded helm, puts it on backwards, wears it for an hour before realising, and tells no one.",
      "{name} tears a page from an old tome, reads it twice, understands nothing, and folds it into a small hat.",
      "{name} builds a small cairn atop every suspicious surface they pass, just in case.",
      "{name} attempts to commune with a dungeon toad for strategic insight; the toad blinks slowly and hops away.",
      "{name} locates a length of perfectly good rope, examines it, declares it 'suspicious', and leaves it behind.",
      "{name} improvises a disguise from a discarded cloak and a bucket, then abandons it when the bucket slips.",
      "{name} decides today is a good day to finally learn to whittle and produces something that might be a horse.",
      "{name} adopts an extremely confident walk through a section of the Gauntlet they have never visited before.",
      "{name} makes a small 'X' mark on the floor wherever they have already been, and is alarmed by how many there are.",
      "{name} finds a locked door, rattles it, nods knowingly, and writes 'LOCKED' on the wall beside it.",
      "{name} bribes a dungeon crow with dried meat in exchange for what they describe as 'aerial reconnaissance'.",
      "{name} constructs a bed from moss and leaves, sleeps in it exactly once, and defends the craftsmanship to no one.",
      "{name} places a single crouton — discovered in a coat pocket — onto a flat stone as an offering to fortune."
    ],
    consequences: [
      "{name} stumbles into a concealed pit trap and barely hauls themselves out by a torch bracket.",
      "{name} misjudges a stone ledge and lands badly, twisting an ankle on loose rubble.",
      "{name} wanders into a nest of dungeon hornets and flees, badly stung through the visor gaps.",
      "{name} loses half their provisions when a rotted saddlebag falls into the flooded crypt.",
      "{name} is cornered briefly by a Gauntlet beast before squeezing through a collapsed wall.",
      "{name} drinks from a tainted cistern and spends the night vomiting behind a barricade.",
      "{name} is driven from a hard-won tower chamber by a more powerful warrior at sword-point.",
      "{name} wakes to find their snares empty and their bread cache gnawed to nothing by rats.",
      "{name} barely escapes a Gauntlet-triggered rockfall that buries their camp beneath rubble.",
      "{name} is caught in a flash flood surging through the lower dungeons and swept downstream.",
      "{name} burns a hand on a Gauntlet-conjured fireball that drives warriors toward the keep.",
      "{name} loses their only blade to a deep crack between flagstones and cannot retrieve it.",
      "{name} stumbles into another warrior's trap and springs it — a snare rather than a spike.",
      "{name} is nearly ambushed in the dark but a rat's squeak gives them a half-second warning.",
      "{name} receives a small herald's gift — a single vial of wound salve lowered by raven.",
      "{name} narrowly avoids a crossbow bolt fired from a hidden arrow-slit in the dungeon wall.",
      "{name} discovers a slain warrior and carefully searches the body for weapons and provisions.",
      "{name} is disoriented by summoned fog for hours, walking in circles before finding a rune marker.",
      "{name} drops their pack while fleeing and must survive the night without it.",
      "{name} unknowingly eats a mildly toxic mushroom and spends the afternoon weak and delirious.",
      "{name} is spotted by a rival warband and only escapes by diving into a reed-choked moat.",
      "{name} watches helplessly as a herald's supply drop drifts into another warrior's reach.",
      "{name} develops a fever and is forced to rest against a cold dungeon wall for a full cycle.",
      "{name} loses a boot crossing a tar pit and limps onward with a foot bound in chainmail links.",
      "{name} is nearly caught in a Gauntlet wildfire and survives by sheltering in a stone cistern.",
      "{name} tears open a wound on razor wire strung between two dungeon pillars.",
      "{name} finds themselves caught between two rival warbands — and retreats before either notices.",
      "{name} receives a cryptic herald's note with no provisions — only the words 'seek the east tower'.",
      "{name} is pelted by Gauntlet-conjured hailstones and takes shelter beneath a fallen archway.",
      "{name} runs out of water and searches desperately through the adjoining crypts.",
      "{name} hears a death knell nearby and cannot determine whose it tolled for.",
      "{name} wakes choking from smoke as a Gauntlet fire sweeps the great hall.",
      "{name} is bitten by a dungeon asp but draws the venom with a knife and hot iron.",
      "{name} slips off a stone bridge and loses a vital piece of kit to the current below.",
      "{name} spends the night shivering after their brazier is doused by dungeon seepage.",
      "{name} finds a spike trap with a useful blade but cannot disarm it safely — leaves it.",
      "{name} is exhausted from fighting and rests, drifting into a dangerously light sleep.",
      "{name} is disarmed in a brief scuffle and retreats bruised but alive.",
      "{name} watches another warrior claim a herald's gift of medicine that should have been theirs.",
      "{name} loses their footing on a frost-slicked parapet and slides dangerously close to the drop.",
      "{name} is awoken by the sound of a nearby death knell — too close for comfort.",
      "{name} receives a shallow slash from a thrown blade but manages to keep moving.",
      "{name} finds their salted meat cache has spoiled in the dungeon damp.",
      "{name} is chased by a pack of Gauntlet hounds through two sectors before losing them in the moat.",
      "{name} collapses from exhaustion and sleeps in the open bailey — luckily undiscovered.",
      "{name} tries to climb a keep wall to safety and slides back down, shredding their palms.",
      "{name} stumbles across a slain warrior and realises the kill is very recent.",
      "{name} is overwhelmed briefly by plague-visions from tainted water before recovering.",
      "{name} has their pact betrayed — a promised meeting place in the undercroft was empty.",
      "{name} startles themselves with their own reflection in a puddle and drops half their rations.",
      "{name} sneezes loudly in a silent hall, alerting three nearby warriors.",
      "{name} mistakes a harmless beetle for a Gauntlet horror and sprints into a wall.",
      "{name} sits on a loose stone that immediately flips, launching them into a shallow puddle.",
      "{name} tries to climb a rope that turns out to be a dangling root and falls on their back.",
      "{name} attempts to eat a glowing mushroom and spends an hour convinced they can see music.",
      "{name} waves at what they think is an ally — it’s a skeleton propped against a wall.",
      "{name} loses their footing while doing a ‘heroic leap’ and lands in a pile of old banners.",
      "{name} is chased by an angry raven after accidentally stepping on its shiny pebble stash.",
      "{name} tries to drink from a cistern but slips and dunks their entire head instead.",
      "{name} attempts to sneak past a sleeping warrior but trips over their own scabbard.",
      "{name} mistakes a herald’s horn for a drinking vessel and spends minutes coughing.",
      "{name} tries to impress a nearby warrior with a trick throw and immediately drops their blade.",
      "{name} follows mysterious footprints for half a mile before realizing they are their own.",
      "{name} attempts to tame a dungeon rat; the rat steals their glove and runs off.",
      "{name} confidently kicks open a door that was already open and stumbles forward.",
      "{name} tries to light a torch but sets their own sleeve smoldering instead.",
      "{name} is startled by a harmless bat and flings their pack across the hall.",
      "{name} attempts to leap a small gap, clears it easily, and then trips on flat stone.",
      "{name} misreads a rune marker and spends an hour walking in a perfect circle.",
      "{name} survives the night but wakes to find every passage blocked by new Gauntlet hazards.",
      "{name} accidentally tips over their entire water supply while doing a celebratory stretch.",
      "{name} sits confidently on what turns out to be a Gauntlet-enchanted whoopee cushion of indeterminate origin.",
      "{name} is so startled by their own sneeze that they headbutt a doorframe.",
      "{name} spends three hours hiding from another warrior who was, in fact, a coat rack.",
      "{name} discovers their carefully drawn map is upside-down only after arriving somewhere entirely wrong.",
      "{name} is bested in a staring contest by a dungeon pigeon and feels this says something about them.",
      "{name} confuses a resting warrior for a corpse, attempts to loot them, and has to run immediately.",
      "{name} steps on their own cloak hem and does a full pirouette into a puddle.",
      "{name} tries to open a push door by pulling it for several undignified minutes.",
      "{name} attempts a battle cry and produces instead a noise that makes a nearby warrior burst out laughing.",
      "{name} finds what they believe to be provisions and discovers it is a bag of decorative pebbles.",
      "{name} waves dramatically at a dramatic vista and knocks their own torch into the moat.",
      "{name} attempts to look casual while surrounded by enemies and succeeds only in looking extremely suspicious.",
      "{name} trips over the very decoy they set the previous night and springs their own trap.",
      "{name} is approached by a herald bearing a gift; upon opening it, they find a strongly worded letter from a rival.",
      "{name} accidentally locks themselves inside a store room and spends a full hour working out that the door opens inward.",
      "{name} is dive-bombed by a dungeon owl that mistakes their shiny helmet for a fish.",
      "{name} discovers their sword has been missing from its scabbard for the past three hours and no one noticed.",
      "{name} steps backward to admire their handiwork and reverses directly into a barrel of dungeon brine.",
      "{name} is soundly lectured by a dungeon raven who is apparently furious about something, and retreats.",
      "{name} sits on a cactus-equivalent dungeon plant that no one mentioned would be there.",
      "{name} attempts a dramatic exit through a doorway and walks into the closed half of a double door.",
      "{name} spills the last of their lamp oil trying to pour it in the dark, and must navigate without light.",
      "{name} gives themselves a rousing pep talk in a well, realises it echoes loudly, and flees the reverb.",
      "{name} accidentally scares away their own scouting crow by waving too enthusiastically at its return.",
      "{name} reads a warning inscription above a doorway, laughs at it, goes in anyway, and immediately reverses out.",
      "{name} is hit squarely in the face by a swinging dungeon chandelier that no one else has ever triggered.",
      "{name} tries to start a fire with two damp stones and manages only to bruise both thumbs.",
      "{name} discovers their back-up rations are missing and slowly remembers eating them last night for comfort.",
      "{name} stumbles into a dungeon spider's web, battles it for an embarrassing duration, and exits covered in silk.",
      "{name} slips on a perfectly dry floor for reasons that cannot be explained and sit for a moment in silence.",
      "{name} attempts to dramatically sheathe their weapon and misses the scabbard three times in a row.",
      "{name} gets their gauntlet stuck in a wall crack while reaching for something and must lever themselves free.",
      "{name} drops their torch, catches it, fumbles it, catches it again, then drops it in the moat regardless.",
      "{name} tries to drink from a canteen that turns out to contain a dungeon beetle who had been resting there.",
      "{name} is hit by a herald's supply drop that lands directly on their head rather than at their feet.",
      "{name} trips over a sleeping dungeon cat and lands in a full spread-eagle apology.",
      "{name} accidentally locks eyes with a rival warrior from across the hall and both parties freeze for an entire minute.",
      "{name} reads the time from a sundial in a windowless dungeon and wonders why it isn't working.",
      "{name} puts on a dry pair of socks in great triumph only to step immediately into the one puddle in the chamber.",
      "{name} is startled by their own shadow cast dramatically on a wall and draws their weapon against it.",
      "{name} tries to silently remove armour for stealth purposes and achieves only a prolonged series of loud clangs.",
      "{name} sits down for a rest and discovers the log they've chosen is actually a large, displeased dungeon tortoise.",
      "{name} attempts to climb a ladder and removes it from the wall by pulling instead of gripping.",
      "{name} finds a warm corner of the dungeon, falls asleep almost immediately, and is extremely embarrassed upon waking.",
      "{name} mispronounces a carved inscription aloud and nothing happens, but they feel watched for the rest of the day.",
      "{name} is pelted by a dungeon pigeon who has clearly been waiting for this opportunity.",
      "{name} trips on their own bootlace so many times in one passage that they begin to take it personally.",
      "{name} picks up what appears to be a very dramatic bone relic and is immediately covered in ancient dust.",
      "{name} finds a door they are certain they unlocked yesterday firmly locked again and takes this as a personal slight.",
      "{name} bites down on a piece of dungeon hardtack that turns out to be a small piece of flagstone.",
      "{name} attempts to squeeze through a gap that was definitely bigger last time.",
      "{name} flings their arm out for dramatic emphasis mid-speech and knocks over all of their own equipment.",
      "{name} hides inside a sarcophagus, forgets which way they climbed in, and pops out the wrong end.",
      "{name} waves a torch to check for gas and sets their own eyebrows briefly ablaze.",
      "{name} uses a crumbled wall as cover only for more of it to crumble, leaving them in the open.",
      "{name} spots a suspicious lump under a cloth, steels themselves, whips it back, and discovers a turnip.",
      "{name} steps directly onto the loudest flagstone in the entire dungeon at the worst possible moment.",
      "{name} attempts to tie a quick knot one-handed and produces something that is entirely not a knot.",
      "{name} tries to whisper instructions to a dungeon rat who simply licks its own face in response.",
      "{name} is chased at length by an aggressively territorial dungeon goose that appeared from nowhere.",
      "{name} accidentally puts their armour on inside-out in the dark and only discovers this hours later.",
      "{name} waves confidently to signal an ally, realises too late it is not their ally, and turns it into a stretch.",
      "{name} opens a chest expecting provisions and releases several dozen moths who immediately fill the corridor.",
      "{name} runs face-first into an invisible Gauntlet ward and bounces off in an undignified fashion.",
      "{name} finds an important door locked and spends considerable time picking the lock on the hinge side.",
      "{name} catches a supply drop perfectly, lands well, and immediately trips on the ribbon trailing from it.",
      "{name} is ambushed by a rival, escapes heroically, and then walks back into them rounding the next corner.",
      "{name} discovers their carefully memorised password to a supply cache is apparently not the correct password.",
      "{name} takes a wrong turn into a known dead end and must walk back past the same warrior three times.",
      "{name} attempts to dive through a closing portcullis and ends up sitting in the gap waiting for it to reopen."
    ],
    deaths: [
      "{name} falls into a spiked pit trap hidden beneath loose flagstones.",
      "{name} is caught in a Gauntlet wildfire in the great hall with no passage out.",
      "{name} is overcome by Gauntlet hounds at the edge of the flooded moat.",
      "{name} drinks from a poisoned well — the only water source for miles.",
      "{name} is ambushed by two rival warriors in the catacombs and does not survive.",
      "{name} succumbs to infected wounds after days without salve or fire.",
      "{name} is struck by a Gauntlet lightning bolt on the open parapet.",
      "{name} falls from the highest spire reaching for a herald's supply drop.",
      "{name} is crushed by a portcullis the Gauntlet drops without warning.",
      "{name} accepts a herald's gift that was laced — a trap laid by the Gauntlet masters.",
      "{name} is caught in a deadfall trap and found by the warrior who set it.",
      "{name} drowns after being driven into the flooded lower crypts during a chase.",
      "{name} makes a desperate charge at the central keep and does not return.",
      "{name} is felled by dungeon hornet venom after a sustained swarm attack.",
      "{name} freezes on the open moor after losing their shelter to a flash flood.",
      "{name} is betrayed by a sworn pact-brother at the worst possible moment.",
      "{name} is buried alive when a dungeon tunnel collapses around them.",
      "{name} takes a fatal step across a Gauntlet ward-line and is consumed by it.",
      "{name} starves after a sennight without finding food or clean water.",
      "{name} slips on a single loose pebble and tumbles dramatically into a forgotten oubliette.",
      "{name} mistakes a Gauntlet ward-line for decorative trim and steps directly into oblivion.",
      "{name} challenges a dungeon statue to a duel and is crushed when it topples over.",
      "{name} attempts to ride a Gauntlet hound like a steed; the hound disagrees violently.",
      "{name} pokes a glowing fungus that erupts in a blinding flash, sending them off a parapet.",
      "{name} tries to juggle three daggers to impress a rival and immediately regrets it fatally.",
      "{name} salutes a herald’s banner so vigorously they lose balance and fall from the battlements.",
      "{name} mistakes a deep well for a shallow puddle and steps confidently into the void.",
      "{name} attempts to scare off a dungeon wolf by roaring — the wolf is not impressed.",
      "{name} pulls a mysterious lever labeled 'DO NOT TOUCH' and is never seen again.",
      "{name} is overwhelmed in a final confrontation, and the death knell tolls.",
      "{name} sits in a chair labeled 'DO NOT SIT' and is launched directly through the ceiling.",
      "{name} challenges a dungeon door to a kicking contest and loses on a technicality when the ceiling falls.",
      "{name} attempts to describe a trap to a nearby warrior using hand gestures and accidentally triggers it.",
      "{name} trips over a victory banner they have prematurely hung for themselves.",
      "{name} is undone by a dungeon tortoise that has been very slowly chasing them for three days.",
      "{name} attempts to negotiate with a Gauntlet hazard, presenting a reasoned argument that does not sway it.",
      "{name} tries to dramatically remove a weapon from a stone plinth and removes the stone plinth from the floor instead.",
      "{name} reads 'EXIT' above a door, steps through, and discovers the sign was aspirational.",
      "{name} is defeated in a staring contest by a Gauntlet beast, who considers this a formal challenge accepted.",
      "{name} plays dead so convincingly that two scavenging rivals take everything they own and leave nothing.",
      "{name} writes a lengthy final speech, reads it aloud in full, and is ambushed during the curtain call.",
      "{name} attempts to take cover behind a painted-on door that is not actually a door.",
      "{name} waves off a warning from a dungeon bird, who immediately departs and is not seen to return.",
      "{name} follows a glowing trail of crumbs through the dungeon, reasoning that they look friendly.",
      "{name} attempts to prove a dungeon vine is not poisonous by the most direct method available to them.",
      "{name} mistakes a sleeping Gauntlet beast for a large rock and uses it as a step up.",
      "{name} triumphantly kicks what they believe to be an empty helmet and it is not empty.",
      "{name} tries to outrun a Gauntlet trap set on a three-second delay they themselves set yesterday.",
      "{name} sits down to rest in the one spot in the entire dungeon that is directly above a trapdoor.",
      "{name} successfully disables a spike trap, writes 'DISARMED' on the wall beside it, and leans on it.",
      "{name} is pursued by a single, very determined dungeon goat for two full days before the goat wins.",
      "{name} recites an inscription on a tomb wall aloud, completing it for the first time in recorded history.",
      "{name} spots a suspicious mound of gold coins in an empty room and makes what proves to be a poor decision.",
      "{name} attempts to cool themselves by sitting in a dungeon fountain that is not water.",
      "{name} fixes a stuck door by kicking it repeatedly until it opens, the ceiling comes with it.",
      "{name} leans against a wall for a well-earned rest; the wall has been slowly rotating for several hours.",
      "{name} mistakes a Gauntlet portal for a decorative archway and steps through it with great confidence.",
      "{name} receives a cryptic final warning from the dungeon raven and replies 'noted' before doing the opposite.",
      "{name} attempts to cheat at a Gauntlet trial they did not know was being observed.",
      "{name} is outwitted by the 'DO NOT TOUCH' lever a second time, and this time the Gauntlet is less forgiving."
    ]
  };

  window.EVENT_POOLS = EVENT_POOLS;
  if (typeof window.onEventsReady === 'function') {
    window.onEventsReady(EVENT_POOLS);
  }
})();
