// events.js — Gothic Gauntlet event pools (50 actions · 50 consequences · 20 deaths)
(function() {
  const EVENT_POOLS = {
    actions: [
      "{name} scales the ruined battlements and surveys the Gauntlet from above.",
      "{name} sets a wire snare across a dark corridor using a frayed crossbow string.",
      "{name} drinks from a stone font, refilling a cracked leather canteen.",
      "{name} fashions a crude pike from a broken lance and stolen rope.",
      "{name} ambushes a lesser warrior and drives them from a cache of salted provisions.",
      "{name} digs a shallow pit trap in the mud and covers it with straw and armour scraps.",
      "{name} forms a silent pact with a nearby warrior using the old hand-signs.",
      "{name} raids an unguarded supply chest while its keeper sleeps behind a barricade.",
      "{name} retreats into the catacombs and waits out the night among the old bones.",
      "{name} smears ash and mud across their face and gorget for concealment.",
      "{name} hunts a rival through two darkened halls before losing them at a collapsed portcullis.",
      "{name} binds a gash with strips of linen torn from a dead monk's robe.",
      "{name} tests a cluster of wild mushrooms carefully before eating any.",
      "{name} lights a small torch to signal heralds and ward off the dungeon cold.",
      "{name} wades through a flooded crypt to shake off pursuers.",
      "{name} constructs a barricade of broken pews and iron candlesticks before nightfall.",
      "{name} lures a rival toward a crumbling floor section with a thrown stone.",
      "{name} backtracks along their own path to confuse anyone following their torchlight.",
      "{name} observes two other warriors from behind a shattered stained-glass window.",
      "{name} claims a high tower chamber and blocks the door with a heavy stone altar.",
      "{name} crafts a sling from a leather baldric and a river stone.",
      "{name} tracks a warrior's bootprints through soft dungeon silt for half a mile.",
      "{name} dismantles a deadfall trap and repurposes its chains and counterweights.",
      "{name} charges the central keep at dawn in a calculated raid for provisions.",
      "{name} sleeps in a stone sarcophagus, barely breathing, while footsteps echo past.",
      "{name} lowers themselves on a rope of knotted monk's robes into a lower vault.",
      "{name} feigns a mortal wound to draw another warrior into an exposed position.",
      "{name} harvests medicinal lichen from a damp dungeon wall.",
      "{name} climbs to the highest spire to scan the Gauntlet's full breadth.",
      "{name} abandons their camp at the last second as a Gauntlet beast closes in.",
      "{name} arranges decoy bedding of straw and armour to mislead searchers.",
      "{name} trades safe passage to a weaker warrior in exchange for dried meat.",
      "{name} disables a rival's spring-loaded blade trap and marks it with a skull as warning.",
      "{name} follows the sound of a death knell to scavenge whatever provisions remain.",
      "{name} hurls loose cobblestones down a spiral staircase at a pursuing warrior.",
      "{name} identifies an edible root pushing through the flagstones and pries it free.",
      "{name} sprints across the open bailey to seize a herald's supply drop first.",
      "{name} holds absolutely still for hours as warriors search the adjoining chamber.",
      "{name} marks safe routes by scratching runes into the dungeon stonework.",
      "{name} tears a cloak into strips and fashions a crude bandage kit.",
      "{name} shadows a rival warband from a safe distance, studying their patrol routes.",
      "{name} splashes through a sewage channel to mask their scent from the Gauntlet hounds.",
      "{name} lifts a dagger from a sleeping warrior's belt without waking them.",
      "{name} drives away a dungeon wolf-pack using brands torn from a burning brazier.",
      "{name} leads a rival into a thorn-choked undercroft and slips away in the dark.",
      "{name} rappels down a sheer interior wall using braided leather reins.",
      "{name} sets three crossbow-string snares in a triangle formation around their camp.",
      "{name} boils water over a smokeless fire of dried dung before drinking it.",
      "{name} signals a distant ally by angling a polished shield to catch torchlight.",
      "{name} attempts to intimidate a dungeon rat, only for the rat to stare back unimpressed.",
      "{name} practices a heroic battle pose in a cracked mirror before realizing another warrior is watching.",
      "{name} mistakes a decorative gargoyle for a Gauntlet beast and apologizes to it politely.",
      "{name} tries to skip a stone across a flooded crypt and is delighted when it actually works.",
      "{name} challenges their own echo to a duel and declares victory after a dramatic pause.",
      "{name} fashions a ‘lucky charm’ from two bones and a bent spoon, convinced it hums with power.",
      "{name} attempts to pet a dungeon cat, which immediately steals a strip of their rations.",
      "{name} whispers a rousing speech to a suit of rusted armor, feeling oddly encouraged afterward.",
      "{name} tests a mysterious glowing mushroom by poking it with a stick… which now glows too.",
      "{name} practices stealth by sneaking past an empty hallway with exaggerated care.",
      "{name} tries to barter with a raven using shiny pebbles; the raven takes them all and leaves.",
      "{name} reenacts a legendary duel using a broom handle before tripping over their own cloak.",
      "{name} attempts to decipher ancient runes that turn out to be a child’s doodles in the dust.",
      "{name} salutes a herald’s banner only to realize it’s just a torn curtain caught on a spike.",
      "{name} invents a victory song and hums it loudly enough to alert three nearby warriors.",
      "{name} attempts to juggle three dungeon skulls, succeeding for exactly one glorious second.",
      "{name} mistakes a pile of rubble for a sleeping beast and tiptoes around it dramatically.",
      "{name} tries to train a dungeon beetle to fetch pebbles; the beetle wanders off immediately.",
      "{name} practices their ‘heroic stride’ across the bailey, tripping on the first loose flagstone.",
      "{name} attempts to intimidate a torch sconce into giving more light by glaring at it intensely.",
      "{name} hides a reserve of black bread under a loose flagstone, memorising the location."
    ],
    consequences: [
      "{name} stumbles into a concealed pit trap and barely hauls themselves out by a torch bracket.",
      "{name} misjudges a stone ledge and lands badly, twisting an ankle on loose rubble.",
      "{name} wanders into a nest of dungeon hornets and flees, badly stung through the visor gaps.",
      "{name} loses half their provisions when a rotted saddlebag falls into the flooded crypt.",
      "{name} is cornered briefly by a Gauntlet beast before squeezing through a collapsed wall.",
      "{name} drinks from a tainted cistern and spends the night vomiting behind a barricade.",
      "{name} is driven from a hard-won tower chamber by a more powerful warrior at sword-point.",
      "{name} wakes to find their snares empty and their bread cache gnawed to nothing by rats.",
      "{name} barely escapes a Gauntlet-triggered rockfall that buries their camp beneath rubble.",
      "{name} is caught in a flash flood surging through the lower dungeons and swept downstream.",
      "{name} burns a hand on a Gauntlet-conjured fireball that drives warriors toward the keep.",
      "{name} loses their only blade to a deep crack between flagstones and cannot retrieve it.",
      "{name} stumbles into another warrior's trap and springs it — a snare rather than a spike.",
      "{name} is nearly ambushed in the dark but a rat's squeak gives them a half-second warning.",
      "{name} receives a small herald's gift — a single vial of wound salve lowered by raven.",
      "{name} narrowly avoids a crossbow bolt fired from a hidden arrow-slit in the dungeon wall.",
      "{name} discovers a slain warrior and carefully searches the body for weapons and provisions.",
      "{name} is disoriented by summoned fog for hours, walking in circles before finding a rune marker.",
      "{name} drops their pack while fleeing and must survive the night without it.",
      "{name} unknowingly eats a mildly toxic mushroom and spends the afternoon weak and delirious.",
      "{name} is spotted by a rival warband and only escapes by diving into a reed-choked moat.",
      "{name} watches helplessly as a herald's supply drop drifts into another warrior's reach.",
      "{name} develops a fever and is forced to rest against a cold dungeon wall for a full cycle.",
      "{name} loses a boot crossing a tar pit and limps onward with a foot bound in chainmail links.",
      "{name} is nearly caught in a Gauntlet wildfire and survives by sheltering in a stone cistern.",
      "{name} tears open a wound on razor wire strung between two dungeon pillars.",
      "{name} finds themselves caught between two rival warbands — and retreats before either notices.",
      "{name} receives a cryptic herald's note with no provisions — only the words 'seek the east tower'.",
      "{name} is pelted by Gauntlet-conjured hailstones and takes shelter beneath a fallen archway.",
      "{name} runs out of water and searches desperately through the adjoining crypts.",
      "{name} hears a death knell nearby and cannot determine whose it tolled for.",
      "{name} wakes choking from smoke as a Gauntlet fire sweeps the great hall.",
      "{name} is bitten by a dungeon asp but draws the venom with a knife and hot iron.",
      "{name} slips off a stone bridge and loses a vital piece of kit to the current below.",
      "{name} spends the night shivering after their brazier is doused by dungeon seepage.",
      "{name} finds a spike trap with a useful blade but cannot disarm it safely — leaves it.",
      "{name} is exhausted from fighting and rests, drifting into a dangerously light sleep.",
      "{name} is disarmed in a brief scuffle and retreats bruised but alive.",
      "{name} watches another warrior claim a herald's gift of medicine that should have been theirs.",
      "{name} loses their footing on a frost-slicked parapet and slides dangerously close to the drop.",
      "{name} is awoken by the sound of a nearby death knell — too close for comfort.",
      "{name} receives a shallow slash from a thrown blade but manages to keep moving.",
      "{name} finds their salted meat cache has spoiled in the dungeon damp.",
      "{name} is chased by a pack of Gauntlet hounds through two sectors before losing them in the moat.",
      "{name} collapses from exhaustion and sleeps in the open bailey — luckily undiscovered.",
      "{name} tries to climb a keep wall to safety and slides back down, shredding their palms.",
      "{name} stumbles across a slain warrior and realises the kill is very recent.",
      "{name} is overwhelmed briefly by plague-visions from tainted water before recovering.",
      "{name} has their pact betrayed — a promised meeting place in the undercroft was empty.",
      "{name} startles themselves with their own reflection in a puddle and drops half their rations.",
      "{name} sneezes loudly in a silent hall, alerting three nearby warriors.",
      "{name} mistakes a harmless beetle for a Gauntlet horror and sprints into a wall.",
      "{name} sits on a loose stone that immediately flips, launching them into a shallow puddle.",
      "{name} tries to climb a rope that turns out to be a dangling root and falls on their back.",
      "{name} attempts to eat a glowing mushroom and spends an hour convinced they can see music.",
      "{name} waves at what they think is an ally — it’s a skeleton propped against a wall.",
      "{name} loses their footing while doing a ‘heroic leap’ and lands in a pile of old banners.",
      "{name} is chased by an angry raven after accidentally stepping on its shiny pebble stash.",
      "{name} tries to drink from a cistern but slips and dunks their entire head instead.",
      "{name} attempts to sneak past a sleeping warrior but trips over their own scabbard.",
      "{name} mistakes a herald’s horn for a drinking vessel and spends minutes coughing.",
      "{name} tries to impress a nearby warrior with a trick throw and immediately drops their blade.",
      "{name} follows mysterious footprints for half a mile before realizing they are their own.",
      "{name} attempts to tame a dungeon rat; the rat steals their glove and runs off.",
      "{name} confidently kicks open a door that was already open and stumbles forward.",
      "{name} tries to light a torch but sets their own sleeve smoldering instead.",
      "{name} is startled by a harmless bat and flings their pack across the hall.",
      "{name} attempts to leap a small gap, clears it easily, and then trips on flat stone.",
      "{name} misreads a rune marker and spends an hour walking in a perfect circle.",
      "{name} survives the night but wakes to find every passage blocked by new Gauntlet hazards."
    ],
    deaths: [
      "{name} falls into a spiked pit trap hidden beneath loose flagstones.",
      "{name} is caught in a Gauntlet wildfire in the great hall with no passage out.",
      "{name} is overcome by Gauntlet hounds at the edge of the flooded moat.",
      "{name} drinks from a poisoned well — the only water source for miles.",
      "{name} is ambushed by two rival warriors in the catacombs and does not survive.",
      "{name} succumbs to infected wounds after days without salve or fire.",
      "{name} is struck by a Gauntlet lightning bolt on the open parapet.",
      "{name} falls from the highest spire reaching for a herald's supply drop.",
      "{name} is crushed by a portcullis the Gauntlet drops without warning.",
      "{name} accepts a herald's gift that was laced — a trap laid by the Gauntlet masters.",
      "{name} is caught in a deadfall trap and found by the warrior who set it.",
      "{name} drowns after being driven into the flooded lower crypts during a chase.",
      "{name} makes a desperate charge at the central keep and does not return.",
      "{name} is felled by dungeon hornet venom after a sustained swarm attack.",
      "{name} freezes on the open moor after losing their shelter to a flash flood.",
      "{name} is betrayed by a sworn pact-brother at the worst possible moment.",
      "{name} is buried alive when a dungeon tunnel collapses around them.",
      "{name} takes a fatal step across a Gauntlet ward-line and is consumed by it.",
      "{name} starves after a sennight without finding food or clean water.",
      "{name} slips on a single loose pebble and tumbles dramatically into a forgotten oubliette.",
      "{name} mistakes a Gauntlet ward-line for decorative trim and steps directly into oblivion.",
      "{name} challenges a dungeon statue to a duel and is crushed when it topples over.",
      "{name} attempts to ride a Gauntlet hound like a steed; the hound disagrees violently.",
      "{name} pokes a glowing fungus that erupts in a blinding flash, sending them off a parapet.",
      "{name} tries to juggle three daggers to impress a rival and immediately regrets it fatally.",
      "{name} salutes a herald’s banner so vigorously they lose balance and fall from the battlements.",
      "{name} mistakes a deep well for a shallow puddle and steps confidently into the void.",
      "{name} attempts to scare off a dungeon wolf by roaring — the wolf is not impressed.",
      "{name} pulls a mysterious lever labeled 'DO NOT TOUCH' and is never seen again.",
      "{name} is overwhelmed in a final confrontation, and the death knell tolls."
    ]
  };

  window.EVENT_POOLS = EVENT_POOLS;
  if (typeof window.onEventsReady === 'function') {
    window.onEventsReady(EVENT_POOLS);
  }
})();
